### ISSUE TITLE
Logstash Crashing Due to Error from GitHub Input

### ISSUE THREAD

**Issue by SpencerLN** [logstash-plugins/logstash-input-github#21]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`): 8.4.1
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker): Official Logstash Docker image
3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes): docker
4. How was the Logstash Plugin installed: `/usr/share/logstash/bin/logstash-plugin install logstash-input-github`

**JVM** (e.g. `java -version`): bundled (Temurin-17.0.4+8)

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
Several errors are logged by the GitHub input plugin before Logstash eventually crashes and restarts.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) pipeline definition(s), settings, locale, etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

```
    input {
      github {
        codec => "json"
        secret_token  => "${AUTH_SECRET}"
        port => 5010
        drop_invalid => true
      }
    }

    filter {
      mutate {
        add_field => { "[@metadata][index]" => "github_audit" }
      }
      date {
        match => [ "[repository][pushed_at]", "UNIX", "ISO8601" ]
        target => "[repository][pushed_at]"
      }
      date {
        match => [ "[repository][created_at]", "UNIX", "ISO8601" ]
        target => "[repository][created_at]"
      }
    }

    output {
      elasticsearch {
        hosts => "https://es-http:9200"
        user => "elastic"
        password => "${ELASTICSEARCH_PASSWORD}"
        index => "%{[@metadata][index]}"
        pipeline => "github-audit-pipeline"
        ssl => true
        cacert => "/usr/share/logstash/config/certs/elastic.crt"
        sniffing => false
      }
    }
```

**Provide logs (if relevant)**:
```
[2022-09-13T12:42:51,300][ERROR][org.logstash.Logstash    ][github-audit][90769f607768f706b542e8d25df67351c6484b097a89b3b61228cdb7c577176e] uncaught exception (in thread Ruby-0-Thread-53533: :1)
java.lang.NullPointerException: Cannot invoke "org.jruby.runtime.ThreadContext.getThread()" because "this.mainContext" is null
	at org.jruby.internal.runtime.ThreadService.getMainThread(ThreadService.java:245) ~[jruby.jar:?]
	at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1995) ~[jruby.jar:?]
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:116) ~[jruby.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-09-13T12:42:51,300][ERROR][org.logstash.Logstash    ][github-audit][90769f607768f706b542e8d25df67351c6484b097a89b3b61228cdb7c577176e] uncaught exception (in thread Ruby-0-Thread-53462: :1)
java.lang.NullPointerException: Cannot invoke "org.jruby.runtime.ThreadContext.getThread()" because "this.mainContext" is null
	at org.jruby.internal.runtime.ThreadService.getMainThread(ThreadService.java:245) ~[jruby.jar:?]
	at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1995) ~[jruby.jar:?]
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:116) ~[jruby.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-09-13T12:42:51,298][ERROR][org.logstash.Logstash    ][github-audit][90769f607768f706b542e8d25df67351c6484b097a89b3b61228cdb7c577176e] uncaught exception (in thread Ruby-0-Thread-53700: :1)
java.lang.NullPointerException: Cannot invoke "org.jruby.runtime.ThreadContext.getThread()" because "this.mainContext" is null
	at org.jruby.internal.runtime.ThreadService.getMainThread(ThreadService.java:245) ~[jruby.jar:?]
	at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1995) ~[jruby.jar:?]
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:116) ~[jruby.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-09-13T12:42:51,300][ERROR][org.logstash.Logstash    ][github-audit][90769f607768f706b542e8d25df67351c6484b097a89b3b61228cdb7c577176e] uncaught exception (in thread Ruby-0-Thread-52950: :1)
java.lang.NullPointerException: Cannot invoke "org.jruby.runtime.ThreadContext.getThread()" because "this.mainContext" is null
	at org.jruby.internal.runtime.ThreadService.getMainThread(ThreadService.java:245) ~[jruby.jar:?]
	at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1995) ~[jruby.jar:?]
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:116) ~[jruby.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-09-13T12:42:51,304][ERROR][logstash.inputs.github   ][github-audit][90769f607768f706b542e8d25df67351c6484b097a89b3b61228cdb7c577176e] Error while stopping FTW::WebServer {:exception=>"closed stream", :backtrace=>["org/jruby/RubyIO.java:1326:in `syswrite'", "/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/ftw-0.0.49/lib/ftw/server.rb:94:in `stop'", "/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/ftw-0.0.49/lib/ftw/webserver.rb:35:in `stop'", "/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-input-github-3.0.9/lib/logstash/inputs/github.rb:49:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:410:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:401:in `block in start_input'"]}
[2022-09-13T12:42:51,332][ERROR][logstash.javapipeline    ][github-audit][90769f607768f706b542e8d25df67351c6484b097a89b3b61228cdb7c577176e] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:github-audit
  Plugin: <LogStash::Inputs::GitHub codec=><LogStash::Codecs::JSON id=>"json_606d282c-fd52-4070-9855-959cf7fc542f", enable_metric=>true, charset=>"UTF-8">, drop_invalid=>true, id=>"90769f607768f706b542e8d25df67351c6484b097a89b3b61228cdb7c577176e", port=>5010, secret_token=>"", enable_metric=>true, ip=>"0.0.0.0">
  Error: closed stream
  Exception: IOError
  Stack: org/jruby/RubyIO.java:3755:in `select'
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/ftw-0.0.49/lib/ftw/server.rb:112:in `block in each_connection'
org/jruby/ext/thread/Mutex.java:171:in `synchronize'
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/ftw-0.0.49/lib/ftw/server.rb:110:in `each_connection'
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/ftw-0.0.49/lib/ftw/webserver.rb:27:in `run'
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-input-github-3.0.9/lib/logstash/inputs/github.rb:44:in `run'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:410:in `inputworker'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:401:in `block in start_input'
```

**Comment by edmocosta** [comment]
Hi @SpencerLN, thanks for reporting!

I ran a few tests with Logasth `8.4.1` on docker and couldn't reproduce this issue! could you please provide more information to help us to recreate the problem, such as the full log on [DEBUG](https://www.elastic.co/guide/en/logstash/current/logging.html#log4j2) mode, any specific configuration you have set, diagnostics, etc? 

Thank you!

**Comment by edmocosta** [comment]
Hi @SpencerLN, I was able to recreate the problem! 

It seems the plugin is failing due to some invalid GitHub request body coming in, in this case, a `""` value.

The JSON specification defines any `value` as a valid JSON, it can be a string in double quotes, a number, true/false, or null. When the request's body is parsed, those values are transformed into their corresponding types. When those types aren't a `Hash` (aka JSON object), it breaks the `LogStash::Event` contract, and LogStash crashes. 

I'm wondering how those uncommon webhook messages are reaching the input server. If you are running it in K8s or behind a load balancer, that might be caused by some HTTP liveness/readiness probes pinging the plugin port.
